import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ["latin"] });
const cookieStore = cookies()
const token = cookieStore.get('token')

export const metadata = {
  title: "Around ME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <div className="main-darkContainer">
          <Header token={token} />
            {children}
          </div>
      </body>
    </html>
  );
}
