import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Around ME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        <div className="main-darkContainer">
          
          <div>
            <AuthProvider>
              <Header />
              { children }
            </AuthProvider>
          </div>
        </div>
=======
      <body className={inter.className}>
        <AuthProvider>
          <div className="main-darkContainer">
            <Header />
            {children}
          </div>
        </AuthProvider>
>>>>>>> e2b454520653e1cea4624894e26b71d586b9c928
      </body>
    </html>
  );
}
